const reviewWrap = document.getElementById("reviewWrap");
    const leftArrow = document.querySelector(".left-arrow-wrap .arrow");
    const rightArrow = document.querySelector(".right-arrow-wrap .arrow");
    const imgBox = document.getElementById("imgBox");
    const name = document.getElementById("name");
    const profession = document.getElementById("profession");
    const description = document.getElementById("description");

    let people = [{
        photo: "url('bot.png')",
        name: "MEDI BOT",
        profession: "The Bot Will Chat With You Now...",
        description: "Here is our MEDI to answer and clear for all your questions..! Ask our MEDI in order to get the accurate answers which is generated by analyzing your heath report to give precise information for your Questions."
      },
      {
        photo: "url('remind.png')",
        name: "REMAIND ME",
        profession: "Our Medicine reminder track your medicine...",
        description: "Here is our remainder to help in decreasing medication dispensing errors and wrong dosages. let our remainder make our role simpler in oder make you to take your medicine in correct time"
      },
      {
        photo: "url('map.jpeg')",
        name: "MAPPER",
        profession: "Make your hospitality access easy...",
        description: "Here is our Mapper to make your job simpler by suggesting the nearby Hospitality details in emergency. It gives the current hospitality details by accessing the user current location."
      },
      {
        photo: "url('insurance.jpg')",
        name: "Health Insurance",
        profession: "Your health is our priority..",
        description: "A Health Insurance plan covers the costs that may arise due to any unforeseen hospitalization/ medical procedures. It convers rising Medical cost, Effective financial planning and provides peace of mind in emergency"
      }
    ];

    // set the first person
    imgBox.style.backgroundImage = people[0].photo;
    name.innerText = people[0].name;
    profession.innerText = people[0].profession;
    description.innerText = people[0].description;
    let currentPerson = 0;

    //Select the side where you want to slide
    function slide(side, personNumber) {
      let reviewWrapWidth = reviewWrap.offsetWidth + "px";
      let descriptionHeight = description.offsetHeight + "px";
      //(+ or -)
      let side1symbol = side === "left" ? "" : "-";
      let side2symbol = side === "left" ? "-" : "";

      setTimeout(() => {
        imgBox.style.backgroundImage = people[personNumber].photo;
      }, 0);
      setTimeout(() => {
        description.style.height = descriptionHeight;
      }, 100);
      setTimeout(() => {
        name.innerText = people[personNumber].name;
      }, 200);
      setTimeout(() => {
        profession.innerText = people[personNumber].profession;
      }, 300);
      setTimeout(() => {
        description.innerText = people[personNumber].description;
      }, 400);
    }

    function setNextCardLeft() {
      if (currentPerson === 3) {
        currentPerson = 0;
        slide("left", currentPerson);
      } else {
        currentPerson++;
      }

      slide("left", currentPerson);
    }

    function setNextCardRight() {
      if (currentPerson === 0) {
        currentPerson = 3;
        slide("right", currentPerson);
      } else {
        currentPerson--;
      }

      slide("right", currentPerson);
    }

    leftArrow.addEventListener("click", setNextCardLeft);
    rightArrow.addEventListener("click", setNextCardRight);
